// Code generated by protoc. DO NOT EDIT.
// Minimal stubs - run: protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/product/v1/product_service.proto

package productv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Request/Reply types matching proto.

type CreateProductRequest struct {
	Name                 string
	Description          string
	Category             string
	BasePriceNumerator   int64
	BasePriceDenominator int64
}

type CreateProductReply struct {
	ProductId string
}

type UpdateProductRequest struct {
	ProductId  string
	Name       string
	Description string
	Category   string
}

type UpdateProductReply struct{}

type ActivateProductRequest struct {
	ProductId string
}

type ActivateProductReply struct{}

type DeactivateProductRequest struct {
	ProductId string
}

type DeactivateProductReply struct{}

type ApplyDiscountRequest struct {
	ProductId       string
	Percent         int64
	StartDateUnix   int64
	EndDateUnix     int64
}

type ApplyDiscountReply struct{}

type RemoveDiscountRequest struct {
	ProductId string
}

type RemoveDiscountReply struct{}

type ArchiveProductRequest struct {
	ProductId string
}

type ArchiveProductReply struct{}

type GetProductRequest struct {
	ProductId string
}

type GetProductReply struct {
	ProductId       string
	Name            string
	Description     string
	Category        string
	BasePrice       string
	EffectivePrice  string
	DiscountPercent *int64
	Status          string
}

type ListProductsRequest struct {
	Category string
	Status   string
	Limit    int32
	Offset   int32
}

type ListProductsReply struct {
	Products []*ProductSummary
	Total    int32
}

type ProductSummary struct {
	ProductId      string
	Name          string
	Description   string
	Category      string
	BasePrice     string
	EffectivePrice string
	Status        string
}

// ProductServiceServer is the server API for ProductService.
type ProductServiceServer interface {
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductReply, error)
	UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductReply, error)
	ActivateProduct(context.Context, *ActivateProductRequest) (*ActivateProductReply, error)
	DeactivateProduct(context.Context, *DeactivateProductRequest) (*DeactivateProductReply, error)
	ApplyDiscount(context.Context, *ApplyDiscountRequest) (*ApplyDiscountReply, error)
	RemoveDiscount(context.Context, *RemoveDiscountRequest) (*RemoveDiscountReply, error)
	ArchiveProduct(context.Context, *ArchiveProductRequest) (*ArchiveProductReply, error)
	GetProduct(context.Context, *GetProductRequest) (*GetProductReply, error)
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsReply, error)
	mustEmbedUnimplementedProductServiceServer()
}

type UnimplementedProductServiceServer struct{}

func (UnimplementedProductServiceServer) CreateProduct(context.Context, *CreateProductRequest) (*CreateProductReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedProductServiceServer) UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedProductServiceServer) ActivateProduct(context.Context, *ActivateProductRequest) (*ActivateProductReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateProduct not implemented")
}
func (UnimplementedProductServiceServer) DeactivateProduct(context.Context, *DeactivateProductRequest) (*DeactivateProductReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateProduct not implemented")
}
func (UnimplementedProductServiceServer) ApplyDiscount(context.Context, *ApplyDiscountRequest) (*ApplyDiscountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyDiscount not implemented")
}
func (UnimplementedProductServiceServer) RemoveDiscount(context.Context, *RemoveDiscountRequest) (*RemoveDiscountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDiscount not implemented")
}
func (UnimplementedProductServiceServer) ArchiveProduct(context.Context, *ArchiveProductRequest) (*ArchiveProductReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveProduct not implemented")
}
func (UnimplementedProductServiceServer) GetProduct(context.Context, *GetProductRequest) (*GetProductReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedProductServiceServer) ListProducts(context.Context, *ListProductsRequest) (*ListProductsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}

type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

// ProductServiceClient is the client API (for tests).
type ProductServiceClient interface {
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductReply, error)
}
type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/product.v1.ProductService/CreateProduct"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/product.v1.ProductService/UpdateProduct"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ActivateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ActivateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/product.v1.ProductService/ActivateProduct"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ActivateProduct(ctx, req.(*ActivateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeactivateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeactivateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/product.v1.ProductService/DeactivateProduct"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeactivateProduct(ctx, req.(*DeactivateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ApplyDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyDiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ApplyDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/product.v1.ProductService/ApplyDiscount"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ApplyDiscount(ctx, req.(*ApplyDiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_RemoveDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).RemoveDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/product.v1.ProductService/RemoveDiscount"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).RemoveDiscount(ctx, req.(*RemoveDiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ArchiveProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ArchiveProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/product.v1.ProductService/ArchiveProduct"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ArchiveProduct(ctx, req.(*ArchiveProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/product.v1.ProductService/GetProduct"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/product.v1.ProductService/ListProducts"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListProducts(ctx, req.(*ListProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.v1.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "CreateProduct", Handler: _ProductService_CreateProduct_Handler},
		{MethodName: "UpdateProduct", Handler: _ProductService_UpdateProduct_Handler},
		{MethodName: "ActivateProduct", Handler: _ProductService_ActivateProduct_Handler},
		{MethodName: "DeactivateProduct", Handler: _ProductService_DeactivateProduct_Handler},
		{MethodName: "ApplyDiscount", Handler: _ProductService_ApplyDiscount_Handler},
		{MethodName: "RemoveDiscount", Handler: _ProductService_RemoveDiscount_Handler},
		{MethodName: "ArchiveProduct", Handler: _ProductService_ArchiveProduct_Handler},
		{MethodName: "GetProduct", Handler: _ProductService_GetProduct_Handler},
		{MethodName: "ListProducts", Handler: _ProductService_ListProducts_Handler},
	},
	Streams:  []grpc.StreamDesc{},
}
